
DROP TABLE OPTION;
CREATE TABLE OPTION (
OPTIONID NUMBER PRIMARY KEY,
BIDQTY NUMBER,
BIDPRICE NUMBER,
ASKQTY NUMBER,
ASKPRICE NUMBER,
NETCHANGE NUMBER,
LTP NUMBER,
IV NUMBER,
VOLUME NUMBER,
CHNGINOI NUMBER,
OI NUMBER,
OPTIONTYPE VARCHAR2(2) --CE:call/PE:put
);


CREATE INDEX idx_OPTION_OPTIONID
   ON OPTION (OPTIONID);


DROP TABLE OPTIONCHAIN;
CREATE TABLE OPTIONCHAIN(
OPTIONCHAINID NUMBER PRIMARY KEY,
STRIKEPRICE NUMBER,
call_optionid NUMBER,
put_optionid NUMBER,
OPTIONCHAINSCREENID NUMBER,
CONSTRAINT FK_OPTIONCHAIN_OPTION_PUT
  FOREIGN KEY (put_optionid)
  REFERENCES OPTION (OPTIONID),
CONSTRAINT FK_OPTIONCHAIN_OPTION_CALL
  FOREIGN KEY (call_optionid)
  REFERENCES OPTION (OPTIONID),
CONSTRAINT FK_OPTIONCHAIN_SCREEN_ID
  FOREIGN KEY (OPTIONCHAINSCREENID)
  REFERENCES OPTIONCHAINSCREEN (OPTIONCHAINSCREENID)  
);

CREATE INDEX idx_OPTIONCHAIN_ID
   ON OPTIONCHAIN (OPTIONCHAINID);

/*
DROP TABLE OPTIONCHAINGRID;
CREATE TABLE OPTIONCHAINGRID(
ID NUMBER PRIMARY KEY,
OPTIONCHAINGRIDID NUMBER,
OPTIONCHAINID NUMBER,
CONSTRAINT FK_OPTIONCHAINGRID_OPTIONCGAIN
  FOREIGN KEY (OPTIONCHAINID)
  REFERENCES OPTIONCHAIN (OPTIONCHAINID)
);

CREATE INDEX idx_OPTIONCHAINGRID_ID
   ON OPTIONCHAINGRID (OPTIONCHAINGRIDID);
*/


DROP TABLE OPTIONCHAINSCREEN;
CREATE TABLE OPTIONCHAINSCREEN (
OPTIONCHAINSCREENID NUMBER PRIMARY KEY,
SYMBOL VARCHAR2(50),
SPOTVALUE NUMBER,
SCREENDATE DATE,
FETCHDATE DATE
/*OPTIONCHAINGRIDID NUMBER,
CONSTRAINT FK_OPTIONCHAINSCREEN_GRID
  FOREIGN KEY (OPTIONCHAINGRIDID)
  REFERENCES OPTIONCHAINGRID (OPTIONCHAINGRIDID)*/
);

CREATE INDEX idx_OPTIONCHAINSCREEN_ID
   ON OPTIONCHAINSCREEN (OPTIONCHAINSCREENID);
CREATE INDEX idx_OPTIONCHAINSCREEN_SYMBOL
   ON OPTIONCHAINSCREEN (SYMBOL);
CREATE INDEX idx_OPTIONCHAINSCREEN_VALUE
   ON OPTIONCHAINSCREEN (SPOTVALUE);
CREATE INDEX idx_OPTIONCHAINSCREEN_SCREENDATE
   ON OPTIONCHAINSCREEN (SCREENDATE);
CREATE INDEX idx_OPTIONCHAINSCREEN_FETCHDATE
   ON OPTIONCHAINSCREEN (FETCHDATE);
   

DROP TABLE hibernate_sequence;
CREATE TABLE hibernate_sequence(
next_val NUMBER
);
INSERT INTO hibernate_sequence  (next_val) VALUES(0);

DROP TABLE OHLC;
CREATE TABLE OHLC(
id VARCHAR2 NOT NULL,
symbol VARCHAR2 NOT NULL,
DATE date NOT NULL,
prevClose NUMBER,
openPrice  NUMBER,
highPrice NUMBER,
lowPrice NUMBER,
closePrice NUMBER,
lastPrice NUMBER,
VWAP NUMBER,
totalTradedQuantity NUMBER,
turnover NUMBER,
noOfTrades NUMBER,
deliverableQty NUMBER,
fetchDateTime DATE
);

CREATE INDEX IDX_OHLC_id ON OHLC (id);
CREATE INDEX IDX_OHLC_symbol ON OHLC (SYMBOL);
CREATE INDEX IDX_OHLC_date ON OHLC (DATE);
	
